ALTER TABLE `custom_ad` MODIFY COLUMN `CustomAdID` INTEGER NOT NULL AUTO_INCREMENT;
ALTER TABLE `custom_ad` DROP FOREIGN KEY `CustomAd_CustomAdTypeID`;
ALTER TABLE `custom_ad` MODIFY COLUMN `CustomAdTypeID` INTEGER NOT NULL;
ALTER TABLE `custom_ad_type` MODIFY COLUMN `CustomAdTypeID` INTEGER NOT NULL AUTO_INCREMENT;
ALTER TABLE `custom_ad` ADD CONSTRAINT `CustomAd_CustomAdTypeID` FOREIGN KEY (`CustomAdTypeID`) REFERENCES `custom_ad_type`(`CustomAdTypeID`) ON DELETE CASCADE ON UPDATE CASCADE;