UPDATE `location` SET `LocationID` = 3,`Image` = '/images/Kuglana-Zetra.jpg' WHERE `location`.`LocationID` = 3;
UPDATE `location` SET `LocationID` = 4,`Image` = '/images/Karting-SpeedXTreme.jpg' WHERE `location`.`LocationID` = 4;
UPDATE `location` SET `LocationID` = 5,`Image` = '/images/Bilijar-BilijarDartKlub69Sarajevo.jpg' WHERE `location`.`LocationID` = 5;
UPDATE `location` SET `LocationID` = 6,`Image` = '/images/Bilijar-BilijarKlubJumpSarajevo.jpg' WHERE `location`.`LocationID` = 6;
UPDATE `location` SET `LocationID` = 7,`Image` = '/images/Bilijar-Mr&MrsCue.jpg' WHERE `location`.`LocationID` = 7;
UPDATE `location` SET `LocationID` = 8,`Image` = '/images/Bilijar-MercurSBC.jpg' WHERE `location`.`LocationID` = 8;
UPDATE `location` SET `LocationID` = 9,`Image` = '/images/Bilijar-SBKPredator.jpg' WHERE `location`.`LocationID` = 9;
UPDATE `location` SET `LocationID` = 10,`Image` = '/images/Bilijar-UnionJack.jpg' WHERE `location`.`LocationID` = 10;
UPDATE `location` SET `LocationID` = 11,`Image` = '/images/Bilijar-DynamicBilijarKlub.jpg' WHERE `location`.`LocationID` = 11;
UPDATE `location` SET `LocationID` = 12,`Image` = '/images/Pikado-Pikado69Sarajevo.jpg' WHERE `location`.`LocationID` = 12;
UPDATE `location` SET `LocationID` = 13,`Image` = '/images/Pikado-Mr&MrsCue.jpg' WHERE `location`.`LocationID` = 13;
UPDATE `location` SET `LocationID` = 14,`Image` = '/images/Pikado-UnionJack.jpg' WHERE `location`.`LocationID` = 14;
UPDATE `location` SET `LocationID` = 15,`Image` = '/images/Pikado-SBKPredator.jpg' WHERE `location`.`LocationID` = 15;
UPDATE `location` SET `LocationID` = 16,`Image` = '/images/Paintbal-JungleSarajevo.jpg' WHERE `location`.`LocationID` = 16;
UPDATE `location` SET `LocationID` = 17,`Image` = '/images/AdrenalinPark-SafetZajko.jpg' WHERE `location`.`LocationID` = 17;
UPDATE `location` SET `LocationID` = 18,`Image` = '/images/AdrenalinPark-ZicaraSarajevo.jpg' WHERE `location`.`LocationID` = 18;
UPDATE `location` SET `LocationID` = 19,`Image` = '/images/AdrenalinPark-PionirskaDolina.jpg' WHERE `location`.`LocationID` = 19;
UPDATE `location` SET `LocationID` = 20,`Image` = '/images/AdrenalinPark-Sunnyland.jpg' WHERE `location`.`LocationID` = 20;
UPDATE `location` SET `LocationID` = 21,`Image` = '/images/Muzej-Zemaljski.jpg' WHERE `location`.`LocationID` = 21;
UPDATE `location` SET `LocationID` = 22,`Image` = '/images/Muzej-SvrzinaKuca.jpg' WHERE `location`.`LocationID` = 22;
UPDATE `location` SET `LocationID` = 23,`Image` = '/images/Muzej-MuzejJevreja.jpeg' WHERE `location`.`LocationID` = 23;
UPDATE `location` SET `LocationID` = 24,`Image` = '/images/Muzej-Sarajevo 1878 – 1918.jpg' WHERE `location`.`LocationID` = 24;
UPDATE `location` SET `LocationID` = 25,`Image` = '/images/Muzej-DespicaKuca.jpg' WHERE `location`.`LocationID` = 25;
UPDATE `location` SET `LocationID` = 26,`Image` = '/images/Muzej-Historijski.jpg' WHERE `location`.`LocationID` = 26;
UPDATE `location` SET `LocationID` = 27,`Image` = '/images/Muzej-GaziHusrevBeg.jpg' WHERE `location`.`LocationID` = 27;
UPDATE `location` SET `LocationID` = 28,`Image` = '/images/Muzej-GaziHusrevBegBiblioteka.jpg' WHERE `location`.`LocationID` = 28;
UPDATE `location` SET `LocationID` = 29,`Image` = '/images/Muzej-Vijecnica.jpeg' WHERE `location`.`LocationID` = 29;
UPDATE `location` SET `LocationID` = 30,`Image` = '/images/Muzej-Muzej književnosti i pozorišne umjetnosti-Galerija “Mak”.jpg' WHERE `location`.`LocationID` = 30;
UPDATE `location` SET `LocationID` = 31,`Image` = '/images/Muzej-Olimpijski.jpg' WHERE `location`.`LocationID` = 31;
UPDATE `location` SET `LocationID` = 32,`Image` = '/images/Muzej-StaraPravoslavnaCrkva.jpg' WHERE `location`.`LocationID` = 32;
UPDATE `location` SET `LocationID` = 33,`Image` = '/images/Muzej-AlijeIzetbegobica.jpg' WHERE `location`.`LocationID` = 33;
UPDATE `location` SET `LocationID` = 34,`Image` = '/images/Muzej- Spomenički kompleks “Tunel spasa”.jpg' WHERE `location`.`LocationID` = 34;
UPDATE `location` SET `LocationID` = 35,`Image` = '/images/Muzej-SarajevskePivare.jpg' WHERE `location`.`LocationID` = 35;
UPDATE `location` SET `LocationID` = 36,`Image` = '/images/Muzej-Bezistan.jpg' WHERE `location`.`LocationID` = 36;
UPDATE `location` SET `LocationID` = 37,`Image` = '/images/Muzej-Svedaha.jpg' WHERE `location`.`LocationID` = 37;
UPDATE `location` SET `LocationID` = 38,`Image` = '/images/Muzej-EscapeRoom.jpg' WHERE `location`.`LocationID` = 38;
UPDATE `location` SET `LocationID` = 39,`Image` = '/images/Muzej-KeyRoomEscape.jpg' WHERE `location`.`LocationID` = 39;
UPDATE `location` SET `LocationID` = 40,`Image` = '/images/Muzej-NoEscapeRoom.jpg' WHERE `location`.`LocationID` = 40;
UPDATE `location` SET `LocationID` = 41,`Image` = '/images/Muzej-FoxInABox.jpg' WHERE `location`.`LocationID` = 41;
UPDATE `location` SET `LocationID` = 42,`Image` = '/images/Muzej-Selfie.jpg' WHERE `location`.`LocationID` = 42;
UPDATE `location` SET `LocationID` = 43,`Image` = '/images/Muzej-RatnogDjetinjstva.jpg' WHERE `location`.`LocationID` = 43;
UPDATE `location` SET `LocationID` = 44,`Image` = '/images/Muzej-OptickihIluzija.jpg' WHERE `location`.`LocationID` = 44;
UPDATE `location` SET `LocationID` = 45,`Image` = '/images/Pozoriste-NarodnoPozoriste.jpg' WHERE `location`.`LocationID` = 45;
UPDATE `location` SET `LocationID` = 46,`Image` = '/images/Pozoriste-PozoristeMladih.jpg' WHERE `location`.`LocationID` = 46;
UPDATE `location` SET `LocationID` = 47,`Image` = '/images/Pozoriste-KameniTeatar.jpg' WHERE `location`.`LocationID` = 47;
UPDATE `location` SET `LocationID` = 48,`Image` = '/images/Pozoriste-SarajevoWarTheater.jpg' WHERE `location`.`LocationID` = 48;
UPDATE `location` SET `LocationID` = 49,`Image` = '/images/Kino-NoviGrad.jpg' WHERE `location`.`LocationID` = 49;
UPDATE `location` SET `LocationID` = 50,`Image` = '/images/Kino-Cinestar.jpg' WHERE `location`.`LocationID` = 50;
UPDATE `location` SET `LocationID` = 51,`Image` = '/images/Kino-MeetingPoint.jpg' WHERE `location`.`LocationID` = 51;
UPDATE `location` SET `LocationID` = 52,`Image` = '/images/Kino-Cineplexx.jpg' WHERE `location`.`LocationID` = 52;
UPDATE `location` SET `LocationID` = 53,`Image` = '/images/Bazeni-OlimpijskiBazenOtoka.jpg' WHERE `location`.`LocationID` = 53;
UPDATE `location` SET `LocationID` = 54,`Image` = '/images/Bazeni-Terme.jpg' WHERE `location`.`LocationID` = 54;
UPDATE `location` SET `LocationID` = 55,`Image` = '/images/Bazeni-West Wood Club&SPA - Hotel Central Sarajev.jpg' WHERE `location`.`LocationID` = 55;
UPDATE `location` SET `LocationID` = 56,`Image` = '/images/Bazeni-Spa & Wellness Centar Malak Regency.jpg' WHERE `location`.`LocationID` = 56;
UPDATE `location` SET `LocationID` = 57,`Image` = '/images/Bazeni-Maab Spa Centar.jpg' WHERE `location`.`LocationID` = 57;
UPDATE `location` SET `LocationID` = 58,`Image` = '/images/Bazeni-Herbal Spa - Ilidza.jpg' WHERE `location`.`LocationID` = 58;
UPDATE `location` SET `LocationID` = 59,`Image` = '/images/Bazeni-HERBAL SPA NOVO SARAJEVO - FOR LADIES ONLY.jpg' WHERE `location`.`LocationID` = 59;
UPDATE `location` SET `LocationID` = 60,`Image` = '/images/Bazeni-Iris Lifestyle Wellness & Spa.jpg' WHERE `location`.`LocationID` = 60;
UPDATE `location` SET `LocationID` = 61,`Image` = '/images/Bazeni-Sundara Balinese Thai Massage.jpg' WHERE `location`.`LocationID` = 61;
UPDATE `location` SET `LocationID` = 62,`Image` = '/images/Bazeni-Herbal Spa Centar.jpg' WHERE `location`.`LocationID` = 62;
UPDATE `location` SET `LocationID` = 63,`Image` = '/images/Bazeni-GOODLIFE Spa Sarajevo.jpg' WHERE `location`.`LocationID` = 63;
UPDATE `location` SET `LocationID` = 64,`Image` = '/images/Bazeni-Ayana spa.jpg' WHERE `location`.`LocationID` = 64;
UPDATE `location` SET `LocationID` = 65,`Image` = '/images/Bazeni-Royal Lotus - Body therapy center.jpg' WHERE `location`.`LocationID` = 65;
UPDATE `location` SET `LocationID` = 66,`Image` = '/images/Bazeni-MAARLAS doo.jpg' WHERE `location`.`LocationID` = 66;
UPDATE `location` SET `LocationID` = 67,`Image` = '/images/Tenis-Teniski centar Stup.jpg' WHERE `location`.`LocationID` = 67;
UPDATE `location` SET `LocationID` = 68,`Image` = '/images/Tenis-Kosevo.jpg' WHERE `location`.`LocationID` = 68;
UPDATE `location` SET `LocationID` = 69,`Image` = '/images/Tenis-Golf klub Sarajevo.jpg' WHERE `location`.`LocationID` = 69;
UPDATE `location` SET `LocationID` = 70,`Image` = '/images/Tenis-Vistafon.jpg' WHERE `location`.`LocationID` = 70;
UPDATE `location` SET `LocationID` = 71,`Image` = '/images/Tenis-Fudbalski tereni benbaša.jpg' WHERE `location`.`LocationID` = 71;
UPDATE `location` SET `LocationID` = 72,`Image` = '/images/AdrenalinPark-VreloBosne.jpg' WHERE `location`.`LocationID` = 72;