START TRANSACTION;

UPDATE `trackimage` SET `TrackImageID` = 2,`Image` = '/track-images/track-image-1.webp' WHERE `trackimage`.`TrackImageID` = 2;
UPDATE `trackimage` SET `TrackImageID` = 3,`Image` = '/track-images/track-image-2.webp' WHERE `trackimage`.`TrackImageID` = 3;
UPDATE `trackimage` SET `TrackImageID` = 4,`Image` = '/track-images/track-image-3.webp' WHERE `trackimage`.`TrackImageID` = 4;
UPDATE `trackimage` SET `TrackImageID` = 5,`Image` = '/track-images/track-image-4.webp' WHERE `trackimage`.`TrackImageID` = 5;
UPDATE `trackimage` SET `TrackImageID` = 6,`Image` = '/track-images/track-image-5.webp' WHERE `trackimage`.`TrackImageID` = 6;
UPDATE `trackimage` SET `TrackImageID` = 7,`Image` = '/track-images/track-image-6.webp' WHERE `trackimage`.`TrackImageID` = 7;
UPDATE `trackimage` SET `TrackImageID` = 8,`Image` = '/track-images/track-image-7.webp' WHERE `trackimage`.`TrackImageID` = 8;
UPDATE `trackimage` SET `TrackImageID` = 9,`Image` = '/track-images/track-image-8.webp' WHERE `trackimage`.`TrackImageID` = 9;
UPDATE `trackimage` SET `TrackImageID` = 10,`Image` = '/track-images/track-image-9.webp' WHERE `trackimage`.`TrackImageID` = 10;
UPDATE `trackimage` SET `TrackImageID` = 11,`Image` = '/track-images/track-image-10.webp' WHERE `trackimage`.`TrackImageID` = 11;
UPDATE `trackimage` SET `TrackImageID` = 12,`Image` = '/track-images/track-image-11.webp' WHERE `trackimage`.`TrackImageID` = 12;
UPDATE `trackimage` SET `TrackImageID` = 13,`Image` = '/track-images/track-image-12.webp' WHERE `trackimage`.`TrackImageID` = 13;
UPDATE `trackimage` SET `TrackImageID` = 14,`Image` = '/track-images/track-image-13.webp' WHERE `trackimage`.`TrackImageID` = 14;
UPDATE `trackimage` SET `TrackImageID` = 15,`Image` = '/track-images/track-image-14.webp' WHERE `trackimage`.`TrackImageID` = 15;
UPDATE `trackimage` SET `TrackImageID` = 16,`Image` = '/track-images/track-image-15.webp' WHERE `trackimage`.`TrackImageID` = 16;
UPDATE `trackimage` SET `TrackImageID` = 17,`Image` = '/track-images/track-image-16.webp' WHERE `trackimage`.`TrackImageID` = 17;
UPDATE `trackimage` SET `TrackImageID` = 18,`Image` = '/track-images/track-image-17.webp' WHERE `trackimage`.`TrackImageID` = 18;
UPDATE `trackimage` SET `TrackImageID` = 19,`Image` = '/track-images/track-image-18.webp' WHERE `trackimage`.`TrackImageID` = 19;
UPDATE `trackimage` SET `TrackImageID` = 20,`Image` = '/track-images/track-image-19.webp' WHERE `trackimage`.`TrackImageID` = 20;
UPDATE `trackimage` SET `TrackImageID` = 21,`Image` = '/track-images/track-image-20.webp' WHERE `trackimage`.`TrackImageID` = 21;
UPDATE `trackimage` SET `TrackImageID` = 22,`Image` = '/track-images/track-image-21.webp' WHERE `trackimage`.`TrackImageID` = 22;
UPDATE `trackimage` SET `TrackImageID` = 23,`Image` = '/track-images/track-image-22.webp' WHERE `trackimage`.`TrackImageID` = 23;
UPDATE `trackimage` SET `TrackImageID` = 24,`Image` = '/track-images/track-image-23.webp' WHERE `trackimage`.`TrackImageID` = 24;
UPDATE `trackimage` SET `TrackImageID` = 25,`Image` = '/track-images/track-image-24.webp' WHERE `trackimage`.`TrackImageID` = 25;
UPDATE `trackimage` SET `TrackImageID` = 26,`Image` = '/track-images/track-image-25.webp' WHERE `trackimage`.`TrackImageID` = 26;
UPDATE `trackimage` SET `TrackImageID` = 27,`Image` = '/track-images/track-image-26.webp' WHERE `trackimage`.`TrackImageID` = 27;
UPDATE `trackimage` SET `TrackImageID` = 28,`Image` = '/track-images/track-image-27.webp' WHERE `trackimage`.`TrackImageID` = 28;
UPDATE `trackimage` SET `TrackImageID` = 29,`Image` = '/track-images/track-image-28.webp' WHERE `trackimage`.`TrackImageID` = 29;
UPDATE `trackimage` SET `TrackImageID` = 30,`Image` = '/track-images/track-image-29.webp' WHERE `trackimage`.`TrackImageID` = 30;
COMMIT;
